name: React Native iOS E2E Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-ios:
      name: e2e-ios-test
      runs-on: macos-latest-xlarge
      env:
        DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
        MAESTRO_ENVIRONMENT: ios
        NODE_ENV: production
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Debug directory structure
          run: |
            echo "Current directory:"
            pwd
            echo "\nDirectory contents:"
            ls -la
            echo "\nFull tree:"
            find . -maxdepth 3 -type d

        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.0'
            bundler-cache: true

        - name: Install xcpretty
          run: gem install xcpretty

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
            cache: 'yarn'

        - name: Install dependencies
          run: |
            for i in 1 2 3; do
              echo "Attempt $i: Installing dependencies..."
              yarn install && break || {
                if [ $i -lt 3 ]; then
                  echo "Retry in 30 seconds..."
                  sleep 30
                else
                  echo "Failed after 3 attempts"
                  exit 1
                fi
              }
            done
            cd ios && bundle install && cd ..

        - name: Cache CocoaPods
          id: pods-cache
          uses: actions/cache@v3
          with:
            path: |
              ios/Pods
              ~/Library/Caches/CocoaPods
            key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-pods-

        - name: Install CocoaPods
          if: steps.pods-cache.outputs.cache-hit != 'true'
          run: |
            cd ios
            pod install
            cd ..

        - name: Clean Xcode caches
          run: |
            cd ios
            rm -rf ~/Library/Developer/Xcode/ModuleCache.noindex/*
            xcodebuild clean -workspace weatherApp.xcworkspace -scheme weatherApp
            cd ..

        - name: Install Maestro CLI
          run: |
            curl -Ls "https://get.maestro.mobile.dev" | bash
            brew tap facebook/fb
            brew install facebook/fb/idb-companion
            echo "${HOME}/.maestro/bin" >> $GITHUB_PATH

        - name: Build iOS App
          run: |
            cd ios
            # First build to generate module maps
            xcodebuild \
              -workspace weatherApp.xcworkspace \
              -scheme weatherApp \
              -configuration Release \
              -destination 'platform=iOS Simulator,name=iPhone 15' \
              build \
              COMPILER_INDEX_STORE_ENABLE=NO \
              | xcpretty
            cd ..

        - name: Start Metro and Run App
          run: |
            # Start metro in background
            yarn start > metro.log 2>&1 &
            METRO_PID=$!
            echo "Waiting for Metro to be ready..."
            while ! grep -q "Metro waiting on" metro.log; do
              if ! kill -0 $METRO_PID 2>/dev/null; then
                echo "Metro process died"
                cat metro.log
                exit 1
              fi
              sleep 1
            done
            # Run the app
            npx react-native run-ios --mode=Release --simulator="iPhone 15" --verbose --no-packager
            sleep 90

        - name: Run Maestro tests
          run: |
            export MAESTRO_DRIVER_STARTUP_TIMEOUT=240000
            export MAESTRO_CLI_NO_ANALYTICS=1
            $HOME/.maestro/bin/maestro test e2e/main-flow-ios.yaml

        - name: Upload logs and artifacts
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: test-artifacts
            path: |
              metro.log
              .maestro/logs/**
              .maestro/tests/**/*.png
              ios/build